#!/usr/bin/env bash
# Compile OF_ROM

cd src/DAFoam4ROM
./Allwmake

cd ../ReducedOrderModeling
wmake
cd ../../

cd applications/solvers/simpleROMFoam
wmake

cd ../../utilities
./Allwmake

#cd ../../doc
#./Allwmake
