#!/usr/bin/env bash
# Clean OF_ROM

rm *.pyc
rm python/*.pyc

cd src/ReducedOrderModeling
wclean
rm Make/options

cd ../DAFoam4ROM
./Allwclean
cd ../../

cd applications/solvers/simpleROMFoam
wclean
rm Make/options

cd ../utilities
./Allwclean

#cd ../../doc
#./Allwclean

