#!/usr/bin/env bash
# Clean OF_ROM

rm -rf python/__pycache__/

cd src/ReducedOrderModeling
wclean

cd ../DAFoam4ROM
./Allwclean
cd ../../

cd applications/solvers/simpleROMFoam
wclean

cd ../../utilities
./Allwclean


