#!/usr/bin/env bash
# Clean OF_ROM

cd src/ReducedOrderModeling
wclean
rm Make/options
cd ../../

cd ./solvers/simpleFoamOfflineROM
wclean
rm Make/options

cd ../simpleFoamOnlineROM
wclean
rm Make/options

