#!/usr/bin/env bash
# Compile DAFoam

echo "************** Compiling prerequisite Libraries **************"
sleep 1

cd myLibs
./Allwmake
cd ../


echo "************** Compiling Incompressible Adjoint Solvers **************"
sleep 1

wmake

