#!/usr/bin/env bash
# Compile OF_ROM

if [ -z "$ROM_CompileMode" ]; then
    export ROM_CompileMode=Opt
fi

function makeSolvers() 
{
    sed -e '1d' Make/options_orig > Make/options
    if [ "$ROM_CompileMode" = "Debug" ]; then
        sed -i '4i\    \-DFULLDEBUG -g -O0 \\' Make/options
    fi
    wmake dep
    cp Make/options_orig Make/options
    if [ "$ROM_CompileMode" = "Debug" ]; then
        sed -i '4i\    \-DFULLDEBUG -g -O0 \\' Make/options
    fi
    wmake 
}


makeSolvers
